export const BILLING_COUNTRIES: { iso: string; name: string }[] = [
  { iso: "AF", name: "Afghanistan" },
  { iso: "AL", name: "Albania" },
  { iso: "DZ", name: "Algeria" },
  { iso: "AR", name: "Argentina" },
  { iso: "AM", name: "Armenia" },
  { iso: "AU", name: "Australia" },
  { iso: "AT", name: "Austria" },
  { iso: "AZ", name: "Azerbaijan" },
  { iso: "BH", name: "Bahrain" },
  { iso: "BD", name: "Bangladesh" },
  { iso: "BE", name: "Belgium" },
  { iso: "BO", name: "Bolivia" },
  { iso: "BA", name: "Bosnia and Herzegovina" },
  { iso: "BR", name: "Brazil" },
  { iso: "BN", name: "Brunei" },
  { iso: "BG", name: "Bulgaria" },
  { iso: "KH", name: "Cambodia" },
  { iso: "CM", name: "Cameroon" },
  { iso: "CA", name: "Canada" },
  { iso: "CL", name: "Chile" },
  { iso: "CN", name: "China" },
  { iso: "CO", name: "Colombia" },
  { iso: "HR", name: "Croatia" },
  { iso: "CY", name: "Cyprus" },
  { iso: "CZ", name: "Czech Republic" },
  { iso: "DK", name: "Denmark" },
  { iso: "EG", name: "Egypt" },
  { iso: "EE", name: "Estonia" },
  { iso: "ET", name: "Ethiopia" },
  { iso: "FI", name: "Finland" },
  { iso: "FR", name: "France" },
  { iso: "GE", name: "Georgia" },
  { iso: "DE", name: "Germany" },
  { iso: "GH", name: "Ghana" },
  { iso: "GR", name: "Greece" },
  { iso: "HK", name: "Hong Kong" },
  { iso: "HU", name: "Hungary" },
  { iso: "IS", name: "Iceland" },
  { iso: "IN", name: "India" },
  { iso: "ID", name: "Indonesia" },
  { iso: "IR", name: "Iran" },
  { iso: "IQ", name: "Iraq" },
  { iso: "IE", name: "Ireland" },
  { iso: "IL", name: "Israel" },
  { iso: "IT", name: "Italy" },
  { iso: "JP", name: "Japan" },
  { iso: "JO", name: "Jordan" },
  { iso: "KZ", name: "Kazakhstan" },
  { iso: "KE", name: "Kenya" },
  { iso: "KW", name: "Kuwait" },
  { iso: "KG", name: "Kyrgyzstan" },
  { iso: "LV", name: "Latvia" },
  { iso: "LB", name: "Lebanon" },
  { iso: "LT", name: "Lithuania" },
  { iso: "LU", name: "Luxembourg" },
  { iso: "MO", name: "Macau" },
  { iso: "MY", name: "Malaysia" },
  { iso: "MV", name: "Maldives" },
  { iso: "MT", name: "Malta" },
  { iso: "MX", name: "Mexico" },
  { iso: "MD", name: "Moldova" },
  { iso: "MN", name: "Mongolia" },
  { iso: "MA", name: "Morocco" },
  { iso: "MM", name: "Myanmar" },
  { iso: "NP", name: "Nepal" },
  { iso: "NL", name: "Netherlands" },
  { iso: "NZ", name: "New Zealand" },
  { iso: "NG", name: "Nigeria" },
  { iso: "NO", name: "Norway" },
  { iso: "OM", name: "Oman" },
  { iso: "PK", name: "Pakistan" },
  { iso: "PS", name: "Palestine" },
  { iso: "PA", name: "Panama" },
  { iso: "PY", name: "Paraguay" },
  { iso: "PE", name: "Peru" },
  { iso: "PH", name: "Philippines" },
  { iso: "PL", name: "Poland" },
  { iso: "PT", name: "Portugal" },
  { iso: "QA", name: "Qatar" },
  { iso: "RO", name: "Romania" },
  { iso: "RU", name: "Russia" },
  { iso: "RW", name: "Rwanda" },
  { iso: "SA", name: "Saudi Arabia" },
  { iso: "SN", name: "Senegal" },
  { iso: "RS", name: "Serbia" },
  { iso: "SG", name: "Singapore" },
  { iso: "SK", name: "Slovakia" },
  { iso: "SI", name: "Slovenia" },
  { iso: "ZA", name: "South Africa" },
  { iso: "KR", name: "South Korea" },
  { iso: "ES", name: "Spain" },
  { iso: "LK", name: "Sri Lanka" },
  { iso: "SE", name: "Sweden" },
  { iso: "CH", name: "Switzerland" },
  { iso: "TW", name: "Taiwan" },
  { iso: "TZ", name: "Tanzania" },
  { iso: "TH", name: "Thailand" },
  { iso: "TN", name: "Tunisia" },
  { iso: "TR", name: "Turkey" },
  { iso: "TM", name: "Turkmenistan" },
  { iso: "UG", name: "Uganda" },
  { iso: "UA", name: "Ukraine" },
  { iso: "AE", name: "United Arab Emirates" },
  { iso: "GB", name: "United Kingdom" },
  { iso: "US", name: "United States" },
  { iso: "UY", name: "Uruguay" },
  { iso: "UZ", name: "Uzbekistan" },
  { iso: "VN", name: "Vietnam" },
  { iso: "YE", name: "Yemen" },
  { iso: "ZM", name: "Zambia" },
  { iso: "ZW", name: "Zimbabwe" },
];

export const STATES_BY_COUNTRY: Record<string, string[]> = {
  IN: [
    "Andaman and Nicobar Islands",
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chandigarh",
    "Chhattisgarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jammu and Kashmir",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Ladakh",
    "Lakshadweep",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Puducherry",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
  ],
  US: [
    "Alabama", "Alaska", "Arizona", "Arkansas", "California",
    "Colorado", "Connecticut", "Delaware", "Florida", "Georgia",
    "Hawaii", "Idaho", "Illinois", "Indiana", "Iowa",
    "Kansas", "Kentucky", "Louisiana", "Maine", "Maryland",
    "Massachusetts", "Michigan", "Minnesota", "Mississippi", "Missouri",
    "Montana", "Nebraska", "Nevada", "New Hampshire", "New Jersey",
    "New Mexico", "New York", "North Carolina", "North Dakota", "Ohio",
    "Oklahoma", "Oregon", "Pennsylvania", "Rhode Island", "South Carolina",
    "South Dakota", "Tennessee", "Texas", "Utah", "Vermont",
    "Virginia", "Washington", "West Virginia", "Wisconsin", "Wyoming",
  ],
  CA: [
    "Alberta", "British Columbia", "Manitoba", "New Brunswick",
    "Newfoundland and Labrador", "Northwest Territories", "Nova Scotia",
    "Nunavut", "Ontario", "Prince Edward Island", "Quebec",
    "Saskatchewan", "Yukon",
  ],
  AU: [
    "Australian Capital Territory", "New South Wales", "Northern Territory",
    "Queensland", "South Australia", "Tasmania", "Victoria", "Western Australia",
  ],
  AE: [
    "Abu Dhabi", "Ajman", "Dubai", "Fujairah",
    "Ras Al Khaimah", "Sharjah", "Umm Al Quwain",
  ],
  GB: [
    "England", "Northern Ireland", "Scotland", "Wales",
  ],
  DE: [
    "Baden-Württemberg", "Bavaria", "Berlin", "Brandenburg", "Bremen",
    "Hamburg", "Hesse", "Lower Saxony", "Mecklenburg-Vorpommern",
    "North Rhine-Westphalia", "Rhineland-Palatinate", "Saarland",
    "Saxony", "Saxony-Anhalt", "Schleswig-Holstein", "Thuringia",
  ],
  MY: [
    "Johor", "Kedah", "Kelantan", "Kuala Lumpur", "Labuan",
    "Melaka", "Negeri Sembilan", "Pahang", "Penang", "Perak",
    "Perlis", "Putrajaya", "Sabah", "Sarawak", "Selangor", "Terengganu",
  ],
  PH: [
    "Abra", "Agusan del Norte", "Agusan del Sur", "Aklan", "Albay",
    "Antique", "Apayao", "Aurora", "Basilan", "Bataan", "Batanes",
    "Batangas", "Benguet", "Biliran", "Bohol", "Bukidnon", "Bulacan",
    "Cagayan", "Camarines Norte", "Camarines Sur", "Camiguin", "Capiz",
    "Catanduanes", "Cavite", "Cebu", "Cotabato", "Davao de Oro",
    "Davao del Norte", "Davao del Sur", "Davao Occidental", "Davao Oriental",
    "Dinagat Islands", "Eastern Samar", "Guimaras", "Ifugao",
    "Ilocos Norte", "Ilocos Sur", "Iloilo", "Isabela", "Kalinga",
    "La Union", "Laguna", "Lanao del Norte", "Lanao del Sur", "Leyte",
    "Maguindanao", "Marinduque", "Masbate", "Metro Manila",
    "Misamis Occidental", "Misamis Oriental", "Mountain Province",
    "Negros Occidental", "Negros Oriental", "Northern Samar",
    "Nueva Ecija", "Nueva Vizcaya", "Occidental Mindoro",
    "Oriental Mindoro", "Palawan", "Pampanga", "Pangasinan",
    "Quezon", "Quirino", "Rizal", "Romblon", "Samar", "Sarangani",
    "Siquijor", "Sorsogon", "South Cotabato", "Southern Leyte",
    "Sultan Kudarat", "Sulu", "Surigao del Norte", "Surigao del Sur",
    "Tarlac", "Tawi-Tawi", "Zambales", "Zamboanga del Norte",
    "Zamboanga del Sur", "Zamboanga Sibugay",
  ],
  SG: ["Central Singapore", "North East", "North West", "South East", "South West"],
};
